global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.0.2.15:9090']
  - job_name: 'docker-host'
    static_configs:
      - targets: ['host.docker.internal:9100'] # Remplacer par l'IP de votre serveur si nécessaire

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

