Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.define "ldap_server" do |ldap|
    ldap.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbooks/deploy_services.yml"
    end
  end

  config.vm.define "monitoring_server" do |monitoring|
    monitoring.vm.provision "shell", inline: <<-SHELL
      docker-compose -f /home/alexis/Bureau/projet-infra/docker/docker-compose.yml up -d
    SHELL
  end
end
